name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # DÃ©clenchement sur push vers main
    paths:
      - '**.md'
      - '**.yml'
      - '**.html'
      - '**.js'
      - '**.css'
      - '**_posts/**'

jobs:
  jekyll-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Version compatible avec Jekyll
          bundler-cache: true

      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Build site
        run: bundle exec jekyll build --baseurl ''

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: /  # Racine de la branche gh-pages
          keep_files: true  # Conserve l'historique des builds

