name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main # Déclenchement sur push vers la branche main
    paths:
      - 'docs/**'  # Chemin vers le dossier contenant les fichiers statiques

jobs:
  deploy-static-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Dossier contenant les fichiers HTML statiques
          destination_dir: /  # Racine de la branche gh-pages
          keep_files: false  # Ne pas conserver les fichiers précédents (optionnel)

